/* =========================================================
   PROJECT: CUSTOMER SHOPPING BEHAVIOR ANALYSIS
   TOOL: SQL
   DATASET: customers table

   PURPOSE:
   This SQL script answers key business questions related to:
   - Revenue performance
   - Discount effectiveness
   - Product performance
   - Customer loyalty and segmentation
   - Subscription behavior
   - Demographic revenue contribution
========================================================= */


/* =========================================================
   1. VIEW ALL CUSTOMER RECORDS
   Purpose:
   - Understand the structure of the dataset
   - Inspect all available fields
========================================================= */
SELECT *
FROM customers;


/* =========================================================
   Q1. TOTAL REVENUE BY GENDER
   Business Objective:
   - Compare how much revenue is generated by male vs female customers
========================================================= */
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;


/* =========================================================
   Q2. HIGH-VALUE CUSTOMERS USING DISCOUNTS
   Business Objective:
   - Identify customers who received a discount but still spent
     more than the overall average purchase amount
========================================================= */
SELECT 
    customer_id, 
    purchase_amount, 
    COUNT(*) OVER () AS total_customers
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount) 
        FROM customers
      );


/* =========================================================
   Q3. TOP 5 HIGHEST-RATED PRODUCTS
   Business Objective:
   - Identify the five products with the best average customer reviews
========================================================= */
SELECT 
    item_purchased AS product, 
    ROUND(AVG(review_rating), 1) AS avg_product_rating
FROM customers
GROUP BY product
ORDER BY AVG(review_rating) DESC
LIMIT 5;


/* =========================================================
   Q4. AVERAGE PURCHASE AMOUNT BY SHIPPING TYPE
   Business Objective:
   - Compare how shipping choice (Standard vs Express)
     affects average customer spending
========================================================= */
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS "Avg Purchase Amount by Shipping Type"
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


/* =========================================================
   Q5. SUBSCRIPTION IMPACT ON SPENDING
   Business Objective:
   - Compare average spending and total revenue between
     subscribed and non-subscribed customers
========================================================= */
SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spent,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY SUM(purchase_amount) DESC;


/* =========================================================
   Q6. PRODUCTS MOST DRIVEN BY DISCOUNTS
   Business Objective:
   - Identify the five products with the highest percentage
     of purchases made using discounts
========================================================= */
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100, 
        2
    ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


/* =========================================================
   Q7. CUSTOMER LOYALTY SEGMENTATION
   Business Objective:
   - Classify customers as:
     * New (1 purchase)
     * Returning (2–10 purchases)
     * Loyal (more than 10 purchases)
   - Show the number of customers in each segment
========================================================= */
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


/* =========================================================
   Q8. TOP 3 MOST PURCHASED PRODUCTS IN EACH CATEGORY
   Business Objective:
   - Identify the best-selling products within each category
========================================================= */
WITH item_counts AS (
    SELECT 
        category, 
        item_purchased,
        COUNT(customer_id) AS total_orders,
        RANK() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;


/* =========================================================
   Q9. REPEAT BUYERS VS SUBSCRIPTION STATUS
   Business Objective:
   - Determine whether frequent buyers (more than 5 purchases)
     are also likely to be subscribed
========================================================= */
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;


/* =========================================================
   Q10. REVENUE CONTRIBUTION BY AGE GROUP
   Business Objective:
   - Identify which age groups contribute the most revenue
========================================================= */
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
